<?php

namespace Fintek\AgentBundle\Repository;

/**
 * SyncRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SyncRepository extends \Doctrine\ORM\EntityRepository
{
}
