#services:
#    backoffice_tpe.example:
#        class: Backoffice\TpeBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

services:
   backoffice_tpe.curlservice:
       class: Backoffice\TpeBundle\Services\CurlService