api_card:
  path: /
  defaults: { _controller: ApiCardBundle:Default:root}

api_card_add:
  path: /card/add
  defaults: { _controller: ApiCardBundle:Card:addCard}
  methods: [POST]

api_card_card:
  path: /card
  defaults: { _controller: ApiCardBundle:Card:index}
  methods: [GET, HEAD]

api_card_getbyid:
  path: /card/{id}
  defaults: { _controller: ApiCardBundle:Card:getById}
  methods: [GET, HEAD]
  requirements:
        id: \d+

api_card_update:
    path:     /card/{id}/update
    defaults: { _controller: ApiCardBundle:Card:updateCard }
    methods: [PUT]
    requirements:
        id: \d+

api_card_delete:
    path:     /card/{id}
    defaults: { _controller: ApiCardBundle:Card:deleteCard }
    methods: [DELETE]
    requirements:
        id: \d+

api_card_field:
  path: /card/{id}/{fields}
  defaults: { _controller: ApiCardBundle:Card:getCardField}
  methods: [GET, HEAD]
  requirements:
        id: \d+
        field: \s+