services:
   api_card.cardservice:
       class: Api\CardBundle\CardService\CardService
       arguments: [ "@doctrine.orm.entity_manager",%secret% ]
   api_card.token_authenticator:
    class: Api\CardBundle\Security\TokenAuthenticator
