services:
   api_card.cardservice:
       class: Api\CardBundle\CardService\CardService
       arguments: [ "@doctrine.orm.entity_manager",%secret% ]

   api_vtc.exeption_listener:
    class: Api\CardBundle\EventListener\ExceptionListener
    tags:
      - { name: kernel.event_listener, event: kernel.exception }

   api_card.token_authenticator:
    class: Api\CardBundle\Security\TokenAuthenticator

   api_card.access_denied_handler:
    class: Api\CardBundle\Security\AccessDeniedHandler

   api_card.firebaseservice:
      class: Api\CardBundle\FirebaseService\FirebaseService
      arguments: [%firebase_host%]