<?php

namespace Api\CardBundle\Repository;
use Api\CardBundle\Entity\Card;
use Doctrine\DBAL\DBALException;
use Doctrine\ORM\ORMException;
use PDOException;
use Exception;

/**
 * cardRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CardRepository extends \Doctrine\ORM\EntityRepository
{
	public function getAll()
	{
		return $this
			->createQueryBuilder('c')
		    ->getQuery()
		    ->getArrayResult();
	}

	public function getById($id) {
	    return $this
		    ->createQueryBuilder('c')
		    ->where("c.id = :id")
		    ->setParameter('id', $id)
		    ->getQuery()
		    ->getArrayResult();
	}

	public function add($data) {
		$em = $this->_em;
		$message = array();
		try{
			$em->persist($data);
			$em->flush();
			$message['success'] = 1;
			$message['message'] = 'Saving successful';
		} catch (DBALException $e) {
            $message['error'] = $e->getCode();
            $message['message'] = $e->getMessage();
        } catch (PDOException $e) {
            $message['error'] = $e->getCode();
            $message['message'] = $e->getMessage();
        } catch (ORMException $e) {
            $message['error'] = $e->getCode();
            $message['message'] = $e->getMessage();
        } catch (Exception $e) {
            $message['error'] = $e->getCode();
            $message['message'] = $e->getMessage();
        }
        return $message;
		//if(null !== $data->getId()) return 1;
	}

	public function update($data) {
	    $qb = $this->createQueryBuilder('c');
		$q = $qb->update()
		    ->set('c.cardNumber', ':cardNumber')
		    ->set('c.pin', ':pin')
		    ->setParameter('cardNumber', $data['cardNumber'])
		    ->setParameter('pin', $data['pin'])
		    ->where("c.id = :id")
		    ->setParameter('id', (int)$data['id'])
		    ->getQuery();
		$card = $q->execute();
		return $card;
	}

	public function delete($id) {
	    $qb = $this->createQueryBuilder('c')
		    ->delete()
		    ->where("c.id = :id")
		    ->setParameter('id', $id)
		    ->getQuery();
		$card = $qb->execute();
		return $card;
	}
}
