<?php

namespace Api\CardBundle\Repository;

/**
 * TpeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TpeRepository extends \Doctrine\ORM\EntityRepository
{
}
