fintek_agent:
    resource: "@FintekAgentBundle/Controller/"
    type:     annotation
    prefix:   /

backoffice_tpe:
    resource: "@BackofficeTpeBundle/Controller/"
    type:     annotation
    prefix:   /backoffice

api_card:
    resource: "@ApiCardBundle/Resources/config/routing.yml"
    prefix:   /api

api_card_home:
  path: /
  defaults: { _controller: ApiCardBundle:Home:index}